/** Rebuild the checked-in geometry YAML from the corrected paper extractions. */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dump } from "js-yaml";

const storyPath = "papers/Story_1996_VocalTractAreaFunctionsMRI/notes.md";
const pbPath = "papers/Peterson_Barney_1952_VowelControl/notes.md";
const rows = readFileSync(storyPath, "utf8")
  .split("**Nasals and plosives")[0]
  .split(/\r?\n/)
  .filter((line) => /^\| \d+ \|/.test(line))
  .map((line) =>
    line
      .split("|")
      .slice(1, -1)
      .map((cell) => cell.trim()),
  );
if (rows.length !== 46 || rows.some((row, i) => Number(row[0]) !== i + 1 || row.length !== 13)) {
  throw new Error("Story vowel table must have 46 numbered rows and 12 configurations");
}
const pbRows = readFileSync(pbPath, "utf8")
  .split("### Formant Amplitudes")[0]
  .split(/\r?\n/)
  .filter((line) => /^\| [^|]+ \| \[/.test(line))
  .map((line) =>
    line
      .split("|")
      .slice(1, -1)
      .map((cell) => cell.trim()),
  );
const symbols = ["IY", "IH", "EH", "AE", "AH", "AA", "AO", "OW", "UH", "UW", "ER", "L"];
const pbWords = [
  "heed",
  "hid",
  "head",
  "had",
  "hud",
  "hod",
  "hawed",
  null,
  "hood",
  "who'd",
  "heard",
  null,
];
const lengths = [42, 42, 40, 42, 44, 44, 44, 44, 44, 46, 44, 46];
const vowels = Object.fromEntries(
  symbols.map((symbol, column) => {
    const areas = rows.map((row) => row[column + 1]);
    const count = lengths[column];
    if (
      areas.slice(count).some(Boolean) ||
      areas.slice(0, count).some((value) => !value || !(Number(value) > 0))
    ) {
      throw new Error(`Incorrect section count or nonpositive area for ${symbol}`);
    }
    const pb = pbRows.find((row) => row[2] === pbWords[column]);
    if (pbWords[column] && !pb) throw new Error(`Missing Peterson & Barney row for ${symbol}`);
    return [
      symbol,
      {
        inventory_key: symbol === "L" ? "L" : `${symbol}1`,
        areas_cm2: areas.slice(0, count).map(Number),
        peterson_barney_hz: pb ? [Number(pb[6]), Number(pb[9]), Number(pb[12])] : null,
      },
    ];
  }),
);
mkdirSync("data/area-functions", { recursive: true });
writeFileSync(
  "data/area-functions/story-1996.yaml",
  "# Generated by scripts/import-story-area-functions.ts from the corrected notes.\n" +
    dump(
      {
        version: "v1",
        citations: [
          "Story, Titze & Hoffman 1996 Table III, p. 547 (subject BS)",
          "Peterson & Barney 1952 Table II (adult male means; comparison only)",
        ],
        section_length_cm: 0.396825,
        // Engineering estimate: fixed regional boundary; not a BS landmark measurement.
        pharynx_fraction: 0.4,
        pharynx_fraction_citation:
          "Engineering estimate: 40% pharynx; informed by Fitch & Giedd 1999 regional morphology, not measured for subject BS",
        model: {
          sound_speed_cm_s: 35000,
          attenuation_neper: 0.007,
          lip_end_correction: 0.8,
          citations: [
            "Story et al. 1996 Sec. III C (350 m/s)",
            "Fant 1960 Eq. A.34-23 (empirical attenuation)",
            "Fant 1960 lip radiation inductance (0.8r end correction)",
          ],
        },
        vowels,
      },
      { lineWidth: 100, noRefs: true, flowLevel: 3 },
    ),
);
